name: Docs Request/Question
description: All things related to docs! Bugs, requests, suggestions, etc.
labels: Documentation
body:
  - type: input
    id: existing-page
    attributes:
      label: Is an existing page relevant?
      placeholder: ex. https://karpenter.sh/v0.16.1/upgrade-guide/

  - type: textarea
    id: relevant-features
    attributes:
      label: What karpenter features are relevant?
    validations:
      required: true

  - type: textarea
    id: docs-improvement
    attributes:
      label: How should the docs be improved?
    validations:
      required: true

  - type: textarea
    id: community-note
    attributes:
      label: Community Note
      description: |
        Please keep this note for the community
      value: |
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
    validations:
      required: true