name: Request
description: Suggest an idea for the roadmap!
labels: feature
body:
  - type: textarea
    id: feature
    attributes:
      label: Tell us about your request
      description: |
        What do you want us to build?
    validations:
      required: true

  - type: textarea
    id: rationale
    attributes:
      label: Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?
      description: |
        What outcome are you trying to achieve, ultimately, and why is it hard/impossible to do right now? What is the impact of not having this problem solved? The more details you can provide, the better we'll be able to understand and solve the problem.
    validations:
      required: true

  - type: textarea
    id: workaround
    attributes:
      label: Are you currently working around this issue?
      description: |
        How are you currently solving this problem?
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: |
        Anything else we should know?

  - type: textarea
    id: attachments
    attributes:
      label: Attachments
      description: |
        If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)
        
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.

  - type: textarea
    id: community-note
    attributes:
      label: Community Note
      description: |
        Please keep this note for the community
      value: |
        * Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
        * Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
        * If you are interested in working on this issue or have submitted a pull request, please leave a comment
    validations:
      required: true